[package]
name = "advent-of-code-2025"
version = "0.2.0"
authors = ["robostac <res@robostac.co.uk"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
